[mysqld]
server_id=12
binlog_format=ROW
log_bin=mysql-bin
innodb_strict_mode=OFF
max_connections = 500
slave_exec_mode=IDEMPOTENT
skip_name_resolve=ON
gtid_mode=ON
enforce_gtid_consistency=ON
report_host=192.168.1.17
report_port=3306
loose_group_replication_start_on_boot=ON
loose_group_replication_local_address=192.168.1.17:33061
loose_group_replication_group_seeds=192.168.3.201:33061,192.168.1.15:33061,192.168.1.17:33061
